peer:
        image: 'event-processing:0.1.0'
        links:
          - zookeeper:zk
          - rabbitmq:rabbitmq
          - db:db
          - dashboard:dashboard
        environment:
          ONYX_ID: 1
          NPEERS: 6
        privileged: true
        expose:
          - "40200"
          - "40200/udp"
          - "1100"
          - "1100/udp"
zookeeper:
        image: 'wurstmeister/zookeeper'
        ports:
          - '2181:2181'
db:
        build: script/postgres
        environment:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - "5432:5432"
dashboard:
        build: script/dashboard
        links:
          - zookeeper:zk
        ports:
          - "3000:3000"
rabbitmq:
        build: script/rabbitmq
        environment:
          RABBITMQ_ERLANG_COOKIE: KXZFFRENCWPZNDVWSRQJ
        ports:
          - "15672:15672"
          - "5672:5672"
          - "1883:1883"
          - "8883:8883"
