peer:
        image: 'event-processing:0.1.0'
        links:
          - zookeeper:zk
          - kafka:kafka
          - db:db
          - kafkacat:kafkacat
          - dashboard:dashboard
        environment:
          ONYX_ID: 1
          NPEERS: 6
        privileged: true
        expose:
          - "40200"
          - "40200/udp"
zookeeper:
        image: 'wurstmeister/zookeeper'
        ports:
          - '2181:2181'
kafka:
        image: 'wurstmeister/kafka'
        environment:
          KAFKA_BROKER_ID: 1
        links:
          - zookeeper:zk
        ports:
          - "9092:9092"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
db:
        image: postgres
        environment:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - "5432:5432"
kafkacat:
        build: script/kafka-meetup-streamer
        links:
          - kafka:kafka
        environment:
          BROKER_LIST: kafka:9092
dashboard:
        build: script/dashboard
        links:
          - zookeeper:zk
        ports:
          - "3000:3000"
